/* Reproduce Elytra's decrypt pattern under Wine BCrypt.
 *
 * NOTE ON WHAT THIS PROVES: test_mode() encrypts and decrypts through the SAME
 * backend, so it demonstrates self-consistency, NOT equivalence to Windows. An
 * implementation wrong in a symmetric way passes it. The fixture tests below are
 * the ones with real evidentiary value: their ciphertext is generated by openssl
 * (see fixtures/generate-fixtures.sh), outside Wine entirely.
 *
 * Original description:
 * Reproduce Elytra's decrypt pattern under Wine BCrypt to test correctness:
 * AES-128, ChainingMode set on the ALGORITHM handle, IV, no padding,
 * IN-PLACE decrypt (pbInput == pbOutput). Round-trip: plaintext -> encrypt
 * (out-of-place) -> decrypt (in-place) -> must equal plaintext.
 *
 * Build:  x86_64-w64-mingw32-gcc bcrypt_inplace_test.c -o t.exe -lbcrypt
 * Run:    wine t.exe   (prints PASS/FAIL per mode/size)
 */
#include <windows.h>
#include <bcrypt.h>
#include <stdio.h>
#include <string.h>

#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS 0
#endif
#ifndef STATUS_DATA_ERROR
#define STATUS_DATA_ERROR ((NTSTATUS)0xC000003E)
#endif

static int test_mode(const WCHAR *mode, const char *label, ULONG len)
{
    BCRYPT_ALG_HANDLE alg = NULL;
    BCRYPT_KEY_HANDLE k1 = NULL, k2 = NULL;
    UCHAR secret[16], iv0[16], iv[16];
    UCHAR keyobj[1024];
    NTSTATUS st;
    ULONG done = 0, objlen = 0, cb = 0;
    UCHAR *plain = malloc(len), *cipher = malloc(len), *work = malloc(len);
    int ok = 0, i, ecb = !wcscmp(mode, BCRYPT_CHAIN_MODE_ECB);

    for (i = 0; i < 16; i++) { secret[i] = i * 7 + 1; iv0[i] = i * 3 + 5; }
    for (i = 0; i < (int)len; i++) plain[i] = (UCHAR)(i * 131 + 17);

    st = BCryptOpenAlgorithmProvider(&alg, BCRYPT_AES_ALGORITHM, NULL, 0);
    if (st) { printf("  [%s] open fail %#lx\n", label, (long)st); goto done; }
    /* set chaining mode on the ALGORITHM (as the driver does) */
    st = BCryptSetProperty(alg, BCRYPT_CHAINING_MODE, (PUCHAR)mode,
                           (ULONG)((wcslen(mode) + 1) * sizeof(WCHAR)), 0);
    if (st) { printf("  [%s] setmode fail %#lx\n", label, (long)st); goto done; }
    BCryptGetProperty(alg, BCRYPT_OBJECT_LENGTH, (PUCHAR)&objlen, sizeof(objlen), &cb, 0);

    st = BCryptGenerateSymmetricKey(alg, &k1, keyobj, objlen, secret, sizeof(secret), 0);
    if (st) { printf("  [%s] genkey1 fail %#lx\n", label, (long)st); goto done; }
    memcpy(iv, iv0, 16);
    st = ecb ? BCryptEncrypt(k1, plain, len, NULL, NULL, 0, cipher, len, &done, 0)
             : BCryptEncrypt(k1, plain, len, NULL, iv, 16, cipher, len, &done, 0);
    if (st) { printf("  [%s] encrypt fail %#lx\n", label, (long)st); goto done; }

    /* fresh key + IV, IN-PLACE decrypt (input ptr == output ptr) */
    st = BCryptGenerateSymmetricKey(alg, &k2, keyobj, objlen, secret, sizeof(secret), 0);
    if (st) { printf("  [%s] genkey2 fail %#lx\n", label, (long)st); goto done; }
    memcpy(work, cipher, len);
    memcpy(iv, iv0, 16);
    st = ecb ? BCryptDecrypt(k2, work, len, NULL, NULL, 0, work, len, &done, 0)
             : BCryptDecrypt(k2, work, len, NULL, iv, 16, work, len, &done, 0);
    if (st) { printf("  [%s] inplace-decrypt fail %#lx\n", label, (long)st); goto done; }

    ok = (memcmp(work, plain, len) == 0);
    printf("  [%s] len=%lu  IN-PLACE round-trip: %s\n", label, len, ok ? "PASS" : "*** FAIL (corrupt) ***");
done:
    if (k1) BCryptDestroyKey(k1);
    if (k2) BCryptDestroyKey(k2);
    if (alg) BCryptCloseAlgorithmProvider(alg, 0);
    free(plain); free(cipher); free(work);
    return ok;
}

/* Decrypt an externally generated fixture with BCRYPT_BLOCK_PADDING.
 * expect_status: STATUS_SUCCESS for the valid fixture, STATUS_DATA_ERROR (the
 * measured Windows status) for the malformed one. */
static int test_fixture(const char *path, const char *label, NTSTATUS expect_status,
                        ULONG expect_len, int check_plaintext)
{
    BCRYPT_ALG_HANDLE alg = NULL;
    BCRYPT_KEY_HANDLE k = NULL;
    UCHAR buf[48], last[16], secret[16], iv[16], keyobj[1024];
    NTSTATUS st;
    ULONG done = 0, objlen = 0, cb = 0;
    FILE *f;
    int ok = 0, i;

    if (!(f = fopen(path, "rb"))) { printf("  [%s] MISSING fixture %s\n", label, path); return 0; }
    if (fread(buf, 1, 48, f) != 48) { printf("  [%s] SHORT fixture\n", label); fclose(f); return 0; }
    fclose(f);
    memcpy(last, buf + 32, 16);

    for (i = 0; i < 16; i++) { secret[i] = i * 7 + 1; iv[i] = i * 3 + 5; }

    if (BCryptOpenAlgorithmProvider(&alg, BCRYPT_AES_ALGORITHM, NULL, 0)) goto done;
    if (BCryptSetProperty(alg, BCRYPT_CHAINING_MODE, (PUCHAR)BCRYPT_CHAIN_MODE_CBC,
                          sizeof(BCRYPT_CHAIN_MODE_CBC), 0)) goto done;
    BCryptGetProperty(alg, BCRYPT_OBJECT_LENGTH, (PUCHAR)&objlen, sizeof(objlen), &cb, 0);
    if (BCryptGenerateSymmetricKey(alg, &k, keyobj, objlen, secret, sizeof(secret), 0)) goto done;

    /* in-place, padded — the shape the retail driver is reported to use */
    st = BCryptDecrypt(k, buf, 48, NULL, iv, 16, buf, 48, &done, BCRYPT_BLOCK_PADDING);

    ok = (st == expect_status);
    if (ok && expect_status == STATUS_SUCCESS)
    {
        if (done != expect_len) ok = 0;
        if (check_plaintext)
            for (i = 0; i < (int)expect_len; i++)
                if (buf[i] != (UCHAR)(i * 131 + 17)) { ok = 0; break; }
    }
    /* Windows advances the IV to the final ciphertext block in BOTH the success
     * and the rejected-padding case. */
    if (memcmp(iv, last, 16)) { printf("  [%s] iv not advanced to last ciphertext block\n", label); ok = 0; }

    printf("  [%s] status=%#lx (want %#lx) len=%lu : %s\n",
           label, (long)st, (long)expect_status, done, ok ? "PASS" : "*** FAIL ***");
done:
    if (k) BCryptDestroyKey(k);
    if (alg) BCryptCloseAlgorithmProvider(alg, 0);
    return ok;
}

int main(void)
{
    int failures = 0;

    /* Proton's launcher does not surface console output; write to a file so the
     * run is capturable the same way padding-matrix.txt is. */
    freopen("bcrypt-inplace.txt", "w", stdout);

    printf("Wine BCrypt in-place AES decrypt round-trip test\n");
    printf(" (self-consistency only - same backend both directions)\n");
    if (!test_mode(BCRYPT_CHAIN_MODE_CBC, "AES-CBC 48B",   48))          failures++;
    if (!test_mode(BCRYPT_CHAIN_MODE_CBC, "AES-CBC 1MB",   1u << 20))    failures++;
    if (!test_mode(BCRYPT_CHAIN_MODE_CBC, "AES-CBC 52MB",  55275056u))   failures++;
    if (!test_mode(BCRYPT_CHAIN_MODE_CFB, "AES-CFB 1MB",   1u << 20))    failures++;
    if (!test_mode(BCRYPT_CHAIN_MODE_ECB, "AES-ECB 1MB",   1u << 20))    failures++;

    printf("Padded decrypt against externally generated fixtures\n");
    if (!test_fixture("fixtures/cbc-small.bin", "valid PKCS7",
                      STATUS_SUCCESS, 47, 1))                            failures++;
    if (!test_fixture("fixtures/cbc-invalid-padding.bin", "invalid PKCS7",
                      STATUS_DATA_ERROR, 0, 0))                          failures++;

    printf("%d failure(s)\n", failures);
    return failures ? 1 : 0;
}
